controllers/PostsController.php
<?php

namespace app\controllers;

use app\models\CommentRecord;
use app\services\ExportService;
use Yii;
use app\models\PostRecord;
use app\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostsController implements the CRUD actions for PostRecord model.
 */
class PostsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PostRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PostRecord model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $postModel = $this->findModel($id);
        $comments = $postModel->comments;
        return $this->render('view', [
            'model' => $postModel,
            'comments' => $comments
        ]);
    }

    /**
     * Creates a new PostRecord model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PostRecord();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $file = UploadedFile::getInstance($model, 'image_url');
            $model->upload($file);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing PostRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $file = UploadedFile::getInstance($model, 'image_url');
            if(!$model->upload($file)){
               $oldImage = Yii::$app->request->post('oldImage', '');
               $model->image_url = $oldImage;
               $model->save();
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PostRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $post = $this->findModel($id);
        if(!empty($post->image_url) && !is_null($post->image_url)){
            $path = Yii::getAlias("@webroot");
            if(file_exists($path . '/' . $post->image_url)){
                unlink($path . '/' . $post->image_url);
            }
        }
        $post->delete();


        return $this->redirect(['index']);
    }

    /**
     * Finds the PostRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return PostRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PostRecord::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionNewComment()
    {
        if(!Yii::$app->request->isAjax){
            return $this->goHome();
        }
        $postId = Yii::$app->request->post('postId');
        $post = $this->findModel($postId);
        $comment = new CommentRecord();
        $comment->load(Yii::$app->request->post());
        if(!empty($comment->text)){
            $comment->save();
        }
        return $this->renderAjax('_comments', ['comments' => $post->comments]);
    }

    public function actionExportToCsv()
    {
        $es = new ExportService();
        $data = $es->generateCsv();
        return Yii::$app->response->sendContentAsFile($data, 'export_' . date('d.m.Y') . '.csv', [
            'mimeType' => 'text/csv',
            'inline'   => false
        ]);
    }

    public function actionDropImage()
    {
        if(!Yii::$app->request->isAjax){
            return $this->goHome();
        }
        $postId = Yii::$app->request->post('postId');
        $post = $this->findModel($postId);
        if(!empty($post->image_url) && !is_null($post->image_url)){
            $path = Yii::getAlias("@webroot");
            if(file_exists($path . '/' . $post->image_url)){
                unlink($path . '/' . $post->image_url);
                $post->image_url = '';
                $post->save();
            }
        }
    }
}

views/posts/_commentform.php
<?php

/* @var app\models\CommentRecord $model */
/* @var integer $postId */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div style="border: #1b6d85 1px solid; margin-bottom: 20px; padding: 10px;">
<?php
$form = ActiveForm::begin(['id' => 'commentForm']); ?>

    <?= $form->field($model, 'id_post')->hiddenInput(['value' => $postId])->label(false) ?>
    <?= $form->field($model, 'text')->textInput(['id' => 'commentField', 'placeholder' => 'Input comment'])->label(false) ?>

    <div class="form-group">
        <?=Html::button('Send', ['id' => 'sendButton', 'onclick' => 'sendComment();'])?>
    </div>

<?php ActiveForm::end(); ?>

</div>

views/posts/_comments.php
<?php
/* @var app\models\CommentRecord [] $comments */


foreach ($comments as $comment) {
    echo '<p style="border: 1px solid black; padding: 5px; margin: 5px; border-radius: 5px;">'.$comment->text.'</p>';
}

views/posts/_form.php
<?php

use app\models\AuthorRecord;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostRecord */
/* @var $form yii\widgets\ActiveForm */

$authors = [];
$raw = AuthorRecord::find()->orderBy('id')->asArray()->all();
foreach ($raw as $item){
    $authors[] = [
        'id' => $item['id'],
        'name' => $item['name'] . ' ' . $item['lastname'],
    ];
}

$js = "
 function dropFile()
   {
       var data = [];  
       data.push({name: 'postId', value : '".$model->id."'});
       $.ajax({
            url: '".Url::to(['posts/drop-image'])."',
            type: 'POST',
            data: data,
            success: function(res){
              $('#oldImage').val('');
              $('#image-div').hide(); 
            },
            error: function(){
                alert('Error!');
            }
        });
   }
";

$this->registerJs($js, View::POS_HEAD);

?>

<div class="post-record-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'id_author')->widget(Select2::class,[
        'data' => ArrayHelper::map($authors, 'id', 'name'),
        'options' => ['placeholder' => 'Choose author'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ])->label('Author') ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'created_at')->widget(DatePicker::class,[
        'type' => DatePicker::TYPE_INPUT,
        'value' => !is_null($model->created_at)? $model->created_at : '',
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd'
        ]
    ]) ?>

    <input type="hidden" name="oldImage" value="<?=$model->image_url?>" id="oldImage">

    <?= $form->field($model, 'image_url')->fileInput() ?>
    <?php
    if(!is_null($model->image_url) && !empty($model->image_url)){
        echo '<div id="image-div" style="margin-bottom: 20px;">';
        echo  '<img id="image" src="'. Yii::getAlias('@web') . '/' . $model->image_url . '" height="150px" alt="image not found">';
        echo  "<a href=\"#\" onclick=\"dropFile();\"><i class='glyphicon glyphicon-remove'></i></a>";
        echo '</div>';
    }
    ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/posts/_search.php
<?php

use app\models\AuthorRecord;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */

$authors = [];
$raw = AuthorRecord::find()->orderBy('id')->asArray()->all();
foreach ($raw as $item){
    $authors[] = [
        'id' => $item['id'],
        'name' => $item['name'] . ' ' . $item['lastname'],
    ];
}
?>

<div class="post-record-search" style="border: #0f0f0f 1px solid; margin: 10px; padding: 5px; border-radius: 10px;">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'id_author')->widget(Select2::class,[
        'data' => ArrayHelper::map($authors, 'id', 'name'),
        'options' => ['placeholder' => 'Choose author'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>

    <?= $form->field($model, 'text') ?>

    <?= $form->field($model, 'created_at')->widget(DatePicker::class,[
        'type' => DatePicker::TYPE_INPUT,
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd'
        ]
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/posts/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\PostRecord */

$this->title = 'Create Post Record';
$this->params['breadcrumbs'][] = ['label' => 'Post Records', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-record-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/posts/index.php
<?php

use kartik\export\ExportMenu;
use kartik\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Post Records';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="post-record-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Post Record', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <p>
        <?= Html::a('Export All to CSV', ['posts/export-to-csv']) ?>
    </p>

    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php
     $columns = [
         ['class' => 'yii\grid\SerialColumn'],
         [
             'attribute' => 'title',
             'filter' => false
         ],
         [
             'format' => 'raw',
             'label' => 'Author',
             'value' => function($model){
                 return $model->author->name . ' ' . $model->author->lastname;
             }
         ],
         [
             'attribute' => 'text',
             'filter' => false
         ],
         [
             'attribute' => 'created_at',
             'filter' => false
         ],

         ['class' => 'yii\grid\ActionColumn'],
     ];
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
        ],
        'export' => false,
        // your toolbar can include the additional full export menu
        'toolbar' => [
            '{export}',
            ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $columns,
                'target' => ExportMenu::TARGET_BLANK,
                'fontAwesome' => true,
                'dropdownOptions' => [
                    'label' => 'Full',
                    'class' => 'btn btn-default',
                    'itemsBefore' => [
                        '<li class="dropdown-header">Export All Data</li>',
                    ],
                ],
                'exportConfig' => [
                    ExportMenu::FORMAT_TEXT => false,
                    ExportMenu::FORMAT_EXCEL => false,
                    ExportMenu::FORMAT_HTML => false,
                    ExportMenu::FORMAT_EXCEL_X => false
                ]
            ])
        ],
    ]); ?>


</div>

views/posts/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\PostRecord */

$this->title = 'Update Post Record: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Post Records', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-record-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/posts/view.php
<?php

use app\models\CommentRecord;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\web\YiiAsset;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\PostRecord */
/* @var $comments [] app\models\CommentRecord */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Post Records', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);

$js = "
 function sendComment()
   {
       var data = $('#commentForm :input').serializeArray();  
       data.push({name: 'postId', value : '".$model->id."'});
       $.ajax({
            url: '".Url::to(['posts/new-comment'])."',
            type: 'POST',
            data: data,
            success: function(res){
                $('#post_comments').html(res);    
                $('#commentField').val('');            
            },
            error: function(){
                alert('Error!');
            }
        });
   }
";

$this->registerJs($js, View::POS_HEAD);
?>
<div class="post-record-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            [
               'format' => 'raw',
               'label' => 'Author',
               'value' => function($model){
                   return $model->author->name . ' ' . $model->author->lastname;
               }
            ],
            'text:ntext',
            'created_at',
            [
              'attribute' => 'image_url',
              'format' => 'raw',
              'value' => function($model){
                   return (is_null($model->image_url) || empty($model->image_url))? '' : '<img src="'.Yii::getAlias('@web') . '/' . $model->image_url.'">';
              }
            ],
        ],
    ]) ?>

    <?=$this->render('_commentform', ['model' => (new CommentRecord()), 'postId' => $model->id])?>
    <div id="post_comments">
       <?=$this->render('_comments', ['comments' => $comments]);?>
    </div>

</div>